import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Camera, Maximize, Minus, Plus, RotateCcw } from 'lucide-react';
import { useArchive } from '../../context/ArchiveContext';
import { ContinueOnPhoneButton } from '../common/ContinueOnPhoneButton';

type Hotspot = { id: string; title: string; description?: string; heading: number; pitch: number; targetType: string; targetId?: string; targetViewpointId?: string };
type Viewpoint = { id: string; title: string; description?: string; initialHeading: number; initialPitch: number; initialZoom: number; panoramaUrl: string; hotspots: Hotspot[] };
type Location = { id: string; title: string; description?: string; city?: string; state?: string; country?: string; viewpoints: Viewpoint[] };
const vertex = `attribute vec2 p; varying vec2 uv; void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`;
const fragment = `precision highp float; varying vec2 uv; uniform sampler2D pano; uniform float yaw; uniform float pitch; uniform float zoom; uniform float aspect;
void main(){float fov=1.35/zoom; vec2 q=(uv-.5)*vec2(aspect,1.)*fov; vec3 d=normalize(vec3(q.x,q.y,1.)); float cp=cos(pitch),sp=sin(pitch),cy=cos(yaw),sy=sin(yaw); d=vec3(d.x, d.y*cp-d.z*sp, d.y*sp+d.z*cp); d=vec3(d.x*cy+d.z*sy,d.y,-d.x*sy+d.z*cy); float lon=atan(d.x,d.z); float lat=asin(clamp(d.y,-1.,1.)); vec2 t=vec2(fract(.5+lon/6.2831853),.5-lat/3.14159265); gl_FragColor=texture2D(pano,t);}`;

export const Heritage360Viewer: React.FC = () => {
  const { heritageContext, navigateTo, showToast } = useArchive();
  const [locations, setLocations] = useState<Location[]>([]);
  const [selectedLocation, setSelectedLocation] = useState<Location | null>(null);
  const [selectedViewpoint, setSelectedViewpoint] = useState<Viewpoint | null>(null);
  const [heading, setHeading] = useState(0); const [pitch, setPitch] = useState(0); const [zoom, setZoom] = useState(1);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [textureError, setTextureError] = useState('');
  const canvasRef = useRef<HTMLCanvasElement>(null); const dragRef = useRef<{ x: number; y: number; heading: number; pitch: number } | null>(null);

  useEffect(() => { let active = true; void fetch('/api/heritage/locations').then(async r => { const j = await r.json(); if (!r.ok || !j.ok) throw new Error(j.message || 'Heritage locations are unavailable.'); return j.data as Location[]; }).then(rows => { if (!active) return; setLocations(rows); const loc = rows.find(x => x.id === heritageContext?.locationId) || rows[0] || null; setSelectedLocation(loc); const vp = loc?.viewpoints.find(x => x.id === heritageContext?.viewpointId) || loc?.viewpoints[0] || null; setSelectedViewpoint(vp); if (vp) { setHeading(heritageContext?.heading ?? vp.initialHeading); setPitch(heritageContext?.pitch ?? vp.initialPitch); setZoom(heritageContext?.zoom ?? vp.initialZoom); } }).catch(e => { if (active) setError(e instanceof Error ? e.message : 'Heritage locations are unavailable.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);

  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas || !selectedViewpoint) return;
    const gl = canvas.getContext('webgl', { alpha: false, antialias: true }); if (!gl) { setTextureError('This browser does not support WebGL panorama viewing.'); return; }
    const compile = (type: number, source: string) => { const shader = gl.createShader(type)!; gl.shaderSource(shader, source); gl.compileShader(shader); if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(shader) || 'WebGL shader failed.'); return shader; };
    let program: WebGLProgram; let texture: WebGLTexture;
    try { program = gl.createProgram()!; gl.attachShader(program, compile(gl.VERTEX_SHADER, vertex)); gl.attachShader(program, compile(gl.FRAGMENT_SHADER, fragment)); gl.linkProgram(program); if (!gl.getProgramParameter(program, gl.LINK_STATUS)) throw new Error('Panorama renderer could not start.'); gl.useProgram(program); const buffer = gl.createBuffer()!; gl.bindBuffer(gl.ARRAY_BUFFER, buffer); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1,-1,1,-1,-1,1,1,1]), gl.STATIC_DRAW); const p = gl.getAttribLocation(program,'p'); gl.enableVertexAttribArray(p); gl.vertexAttribPointer(p,2,gl.FLOAT,false,0,0); texture = gl.createTexture()!; gl.bindTexture(gl.TEXTURE_2D, texture); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR); }
    catch (e) { setTextureError(e instanceof Error ? e.message : 'Panorama renderer could not start.'); return; }
    let active = true;
    const image = new Image(); image.crossOrigin = 'anonymous'; image.onload = () => { if (!active) return; gl.bindTexture(gl.TEXTURE_2D,texture); gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,1); gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,image); setTextureError(''); draw(); }; image.onerror = () => setTextureError('The published panorama could not be loaded.'); image.src = selectedViewpoint.panoramaUrl;
    const draw = () => { if (!active) return; const rect = canvas.getBoundingClientRect(); const dpr = Math.min(window.devicePixelRatio || 1,2); const w = Math.max(1,Math.floor(rect.width*dpr)), h=Math.max(1,Math.floor(rect.height*dpr)); if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;} gl.viewport(0,0,w,h); gl.uniform1i(gl.getUniformLocation(program,'pano'),0); gl.uniform1f(gl.getUniformLocation(program,'yaw'),heading*Math.PI/180); gl.uniform1f(gl.getUniformLocation(program,'pitch'),pitch*Math.PI/180); gl.uniform1f(gl.getUniformLocation(program,'zoom'),zoom); gl.uniform1f(gl.getUniformLocation(program,'aspect'),w/h); gl.drawArrays(gl.TRIANGLE_STRIP,0,4); };
    const observer = new ResizeObserver(draw); observer.observe(canvas); const frame=requestAnimationFrame(draw); return () => { active=false; cancelAnimationFrame(frame); observer.disconnect(); gl.deleteTexture(texture); gl.deleteProgram(program); };
  }, [selectedViewpoint, heading, pitch, zoom]);

  const chooseViewpoint = (vp: Viewpoint) => { setSelectedViewpoint(vp); setHeading(vp.initialHeading); setPitch(vp.initialPitch); setZoom(vp.initialZoom); };
  const openHotspot = useCallback((hotspot: Hotspot) => { if (hotspot.targetType === 'viewpoint' && hotspot.targetViewpointId) { const next = selectedLocation?.viewpoints.find(v => v.id === hotspot.targetViewpointId); if (next) chooseViewpoint(next); return; } if ((hotspot.targetType === 'archive_item' || hotspot.targetType === 'document') && hotspot.targetId) { navigateTo('explorer', { docId: hotspot.targetId }); return; } showToast(hotspot.description || hotspot.title, 'info'); }, [selectedLocation, navigateTo, showToast]);
  const enterFullscreen = () => { const el = canvasRef.current?.parentElement; if (el?.requestFullscreen) void el.requestFullscreen(); };
  const context = selectedLocation && selectedViewpoint ? { locationId: selectedLocation.id, viewpointId: selectedViewpoint.id, heading, pitch, zoom } : undefined;

  return <section className="mx-auto max-w-7xl space-y-5 px-4 py-8 sm:px-6" aria-label="360 degree heritage viewer">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-500">Heritage exploration</p><h1 className="mt-1 font-serif text-3xl font-bold text-white">360° Heritage Viewer</h1><p className="mt-1 max-w-2xl text-sm text-slate-300">Explore published, verified panoramic locations and their archival connections.</p></div>{context && <ContinueOnPhoneButton context={{ type: 'heritage360', ...context }} />}</header>
    {loading ? <div className="rounded-xl border border-slate-700 p-8 text-slate-300">Loading published heritage locations…</div> : error ? <div role="alert" className="rounded-xl border border-rose-400/40 bg-rose-950/30 p-6 text-rose-100">{error}</div> : locations.length === 0 ? <div className="rounded-xl border border-slate-700 bg-slate-900/60 p-10 text-center"><Camera className="mx-auto h-10 w-10 text-amber-400"/><h2 className="mt-3 font-serif text-xl font-bold text-white">No published panoramas yet</h2><p className="mx-auto mt-2 max-w-lg text-sm text-slate-300">The heritage viewer has no verified 360° locations in the archive database. An administrator can add a location, upload a valid panorama, and publish it.</p></div> : <>
      <div className="flex flex-wrap gap-2">{locations.map(loc => <button key={loc.id} onClick={() => { setSelectedLocation(loc); chooseViewpoint(loc.viewpoints[0]); }} className={`rounded-lg border px-3 py-2 text-sm ${selectedLocation?.id===loc.id?'border-amber-400 bg-amber-500/15 text-amber-100':'border-slate-700 text-slate-300'}`}>{loc.title}</button>)}</div>
      {!selectedViewpoint ? <div className="rounded-xl border border-slate-700 p-8 text-slate-300">This location has no published panorama viewpoints.</div> : <>
        <div className="overflow-hidden rounded-2xl border border-slate-700 bg-black"><div className="relative h-[55vh] min-h-[320px] max-h-[720px]"><canvas ref={canvasRef} className="h-full w-full touch-none" aria-label={`${selectedViewpoint.title} 360 degree panorama; drag to look around`} onPointerDown={e=>{dragRef.current={x:e.clientX,y:e.clientY,heading,pitch};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!dragRef.current)return;setHeading(dragRef.current.heading-(e.clientX-dragRef.current.x)*.15);setPitch(Math.max(-85,Math.min(85,dragRef.current.pitch+(e.clientY-dragRef.current.y)*.15)));}} onPointerUp={()=>{dragRef.current=null;}} onWheel={e=>setZoom(z=>Math.max(1,Math.min(3,z+(e.deltaY<0?.1:-.1))))}/>
          {textureError && <div role="alert" className="absolute inset-0 grid place-items-center bg-slate-950/90 p-6 text-center text-sm text-amber-100">{textureError}</div>}
          {selectedViewpoint.hotspots?.map(h=>{const dh=((Number(h.heading)-heading+540)%360)-180; const dp=Number(h.pitch)-pitch; if(Math.abs(dh)>50||Math.abs(dp)>35)return null; const left=50+dh*0.75, top=50-dp*1.15; return <button key={h.id} title={h.title} onClick={()=>openHotspot(h)} style={{left:`${left}%`,top:`${top}%`}} className="absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-amber-500 p-2 text-xs font-bold text-stone-950 shadow-lg" aria-label={`Open hotspot ${h.title}`}>+</button>;})}
          <div className="absolute bottom-3 left-3 flex items-center gap-2 rounded-lg bg-black/65 p-1.5"><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(1,z-.2))} className="rounded p-2 text-white hover:bg-white/10"><Minus size={18}/></button><span className="min-w-12 text-center text-xs text-white">{zoom.toFixed(1)}×</span><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(3,z+.2))} className="rounded p-2 text-white hover:bg-white/10"><Plus size={18}/></button><button aria-label="Reset view" onClick={()=>{setHeading(selectedViewpoint.initialHeading);setPitch(selectedViewpoint.initialPitch);setZoom(selectedViewpoint.initialZoom);}} className="rounded p-2 text-white hover:bg-white/10"><RotateCcw size={17}/></button><button aria-label="Fullscreen" onClick={enterFullscreen} className="rounded p-2 text-white hover:bg-white/10"><Maximize size={17}/></button></div>
        </div><div className="flex flex-wrap items-center justify-between gap-3 bg-slate-900 px-4 py-3"><div><h2 className="font-serif font-bold text-white">{selectedViewpoint.title}</h2><p className="text-xs text-slate-400">{selectedLocation?.title}{selectedLocation?.city ? ` · ${selectedLocation.city}` : ''}</p></div><div className="flex flex-wrap gap-2">{selectedLocation?.viewpoints.map(v=><button key={v.id} onClick={()=>chooseViewpoint(v)} className={`rounded-lg border px-3 py-2 text-xs ${v.id===selectedViewpoint.id?'border-amber-400 text-amber-200':'border-slate-700 text-slate-300'}`}>{v.title}</button>)}</div></div></div>
      </>}
    </>}
  </section>;
};
